//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestarter.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prestarter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Querying BellSoft API.
        /// </summary>
        internal static string BellSoftApiQueryStatus {
            get {
                return ResourceManager.GetString("BellSoftApiQueryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing response from BellSoft API.
        /// </summary>
        internal static string BellSoftApiResponseParsingStatus {
            get {
                return ResourceManager.GetString("BellSoftApiResponseParsingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removing old Java.
        /// </summary>
        internal static string DeletingOldJavaStatus {
            get {
                return ResourceManager.GetString("DeletingOldJavaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading launcher.
        /// </summary>
        internal static string DownloadingLauncherStatus {
            get {
                return ResourceManager.GetString("DownloadingLauncherStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading {0}.
        /// </summary>
        internal static string DownloadingStatus {
            get {
                return ResourceManager.GetString("DownloadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To launch {0} A speciffic Java version required. Download now {1}?.
        /// </summary>
        internal static string ForLauncherStartupSoftwareIsRequiredMessage {
            get {
                return ResourceManager.GetString("ForLauncherStartupSoftwareIsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checksum does not match: {0} != {1}.
        /// </summary>
        internal static string HashsumIsIncorrectError {
            get {
                return ResourceManager.GetString("HashsumIsIncorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred during initialization: the server returned the code {0}.
        /// </summary>
        internal static string InitializationError {
            get {
                return ResourceManager.GetString("InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initialization.
        /// </summary>
        internal static string InitializationStatus {
            get {
                return ResourceManager.GetString("InitializationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Java update available. Would you like us to update it?.
        /// </summary>
        internal static string JavaUpdateAvailableMessage {
            get {
                return ResourceManager.GetString("JavaUpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The launcher process exited unexpectedly.
        /// </summary>
        internal static string LauncherHasExitedTooFastError {
            get {
                return ResourceManager.GetString("LauncherHasExitedTooFastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while processing the response.
        /// </summary>
        internal static string ParsingResponseError {
            get {
                return ResourceManager.GetString("ParsingResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Searching existing launcher.
        /// </summary>
        internal static string SearchingForLauncherStatus {
            get {
                return ResourceManager.GetString("SearchingForLauncherStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting.
        /// </summary>
        internal static string StartingStatus {
            get {
                return ResourceManager.GetString("StartingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unpacking {0}.
        /// </summary>
        internal static string UnpackingStatus {
            get {
                return ResourceManager.GetString("UnpackingStatus", resourceCulture);
            }
        }
    }
}
